version: '2'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 7000:7000
    environment:
      - "SPRING_PROFILES_ACTIVE=default"
      - DOTPAY_CONFIG_CRON_FOR_RUNNING_ANALYSIS=0 0/1 * * * *
      - DOTPAY_CONFIG_CRON_FOR_RUNNING_SUMMARY=0 0 12 * * *
      - DOTPAY_CONFIG_FEE_CAP=100
      - DOTPAY_CONFIG_FEE_PERCENT=0.5
      - DOTPAY_CONFIG_COMMISSION_PERCENT=20
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

