version: '3.8'
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DATASOURCE_PASSWORD
      - MYSQL_DATABASE=$DATASOURCE_SCHEMA
    ports:
      - $SERVICE_LOCAL_PORT:$SERVICE_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: .
    restart: on-failure
    env_file: ./.env
    ports:
      - $SERVICE_LOCAL_PORT:$SERVICE_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{ "spring.datasource.url"  : "jdbc:mysql://mysqldb:$SERVICE_DOCKER_PORT/$DATASOURCE_SCHEMA?useSSL=false", "spring.datasource.username" : "$DATASOURCE_USERNAME", "spring.datasource.password" : "$DATASOURCE_PASSWORD", "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect", "spring.jpa.hibernate.ddl-auto" : "update" }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes:
  db:
